export interface RegistryDefinition {
  id: string;
  name: string;
  country: string;
  countryCode: string;
  apiType: 'rest' | 'bulk_download' | 'scrape' | 'sdmx';
  format: 'json' | 'xml' | 'csv' | 'parquet' | 'html';
  updateFrequency: 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'biannual';
  priority: 1 | 2;
  baseUrl?: string;
  requiresAuth: boolean;
}

export const REGISTRIES: Record<string, RegistryDefinition> = {
  us_propublica: {
    id: 'us_propublica',
    name: 'ProPublica Nonprofit Explorer',
    country: 'United States',
    countryCode: 'US',
    apiType: 'rest',
    format: 'json',
    updateFrequency: 'weekly',
    priority: 1,
    baseUrl: 'https://projects.propublica.org/nonprofits/api/v2',
    requiresAuth: false,
  },
  uk_charity_commission: {
    id: 'uk_charity_commission',
    name: 'UK Charity Commission',
    country: 'United Kingdom',
    countryCode: 'GB',
    apiType: 'rest',
    format: 'json',
    updateFrequency: 'daily',
    priority: 1,
    baseUrl: 'https://api.charitycommission.gov.uk',
    requiresAuth: true,
  },
  uk_360giving: {
    id: 'uk_360giving',
    name: '360Giving GrantNav',
    country: 'United Kingdom',
    countryCode: 'GB',
    apiType: 'rest',
    format: 'json',
    updateFrequency: 'daily',
    priority: 1,
    baseUrl: 'https://grantnav.threesixtygiving.org/api',
    requiresAuth: false,
  },
  iati: {
    id: 'iati',
    name: 'IATI Datastore',
    country: 'International',
    countryCode: 'XX',
    apiType: 'rest',
    format: 'json',
    updateFrequency: 'daily',
    priority: 1,
    baseUrl: 'https://api.iatistandard.org',
    requiresAuth: false,
  },
  un_ocha_fts: {
    id: 'un_ocha_fts',
    name: 'UN OCHA FTS',
    country: 'International',
    countryCode: 'XX',
    apiType: 'rest',
    format: 'json',
    updateFrequency: 'daily',
    priority: 1,
    baseUrl: 'https://api.hpc.tools/v2/public',
    requiresAuth: false,
  },
  oecd_dac: {
    id: 'oecd_dac',
    name: 'OECD DAC CRS',
    country: 'International',
    countryCode: 'XX',
    apiType: 'sdmx',
    format: 'csv',
    updateFrequency: 'quarterly',
    priority: 1,
    baseUrl: 'https://stats.oecd.org/restsdmx/sdmx.ashx',
    requiresAuth: false,
  },
  au_acnc: {
    id: 'au_acnc',
    name: 'ACNC Register',
    country: 'Australia',
    countryCode: 'AU',
    apiType: 'rest',
    format: 'csv',
    updateFrequency: 'weekly',
    priority: 1,
    baseUrl: 'https://data.gov.au/data/api',
    requiresAuth: false,
  },
  ca_cra: {
    id: 'ca_cra',
    name: 'CRA T3010',
    country: 'Canada',
    countryCode: 'CA',
    apiType: 'bulk_download',
    format: 'csv',
    updateFrequency: 'biannual',
    priority: 1,
    requiresAuth: false,
  },
  fr_rna: {
    id: 'fr_rna',
    name: 'France RNA',
    country: 'France',
    countryCode: 'FR',
    apiType: 'rest',
    format: 'json',
    updateFrequency: 'daily',
    priority: 1,
    requiresAuth: false,
  },
  in_ngo_darpan: {
    id: 'in_ngo_darpan',
    name: 'India NGO Darpan',
    country: 'India',
    countryCode: 'IN',
    apiType: 'scrape',
    format: 'html',
    updateFrequency: 'monthly',
    priority: 2,
    requiresAuth: false,
  },
  in_fcra: {
    id: 'in_fcra',
    name: 'India FCRA Portal',
    country: 'India',
    countryCode: 'IN',
    apiType: 'scrape',
    format: 'html',
    updateFrequency: 'monthly',
    priority: 2,
    requiresAuth: false,
  },
};
